version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=schoolmanager
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
  school-manager-backend:
    image: school-manager-backend
    container_name: school-manager-container-backend
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db